// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data_Concurrency.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251224120136_mig_2")]
    partial class mig_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("Name")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Name = "Rıfkı"
                        },
                        new
                        {
                            PersonId = 2,
                            Name = "Hikmet"
                        },
                        new
                        {
                            PersonId = 3,
                            Name = "Rızaettin"
                        },
                        new
                        {
                            PersonId = 4,
                            Name = "Tanju"
                        },
                        new
                        {
                            PersonId = 5,
                            Name = "Mahmut"
                        },
                        new
                        {
                            PersonId = 6,
                            Name = "Tansel"
                        },
                        new
                        {
                            PersonId = 7,
                            Name = "Cugulii"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
