// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Query_Tags.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251219163101_mig_2")]
    partial class mig_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "...",
                            PersonId = 1,
                            Price = 200
                        },
                        new
                        {
                            Id = 2,
                            Description = "...",
                            PersonId = 1,
                            Price = 210
                        },
                        new
                        {
                            Id = 3,
                            Description = "...",
                            PersonId = 2,
                            Price = 220
                        },
                        new
                        {
                            Id = 4,
                            Description = "...",
                            PersonId = 2,
                            Price = 230
                        },
                        new
                        {
                            Id = 5,
                            Description = "...",
                            PersonId = 2,
                            Price = 240
                        },
                        new
                        {
                            Id = 6,
                            Description = "...",
                            PersonId = 3,
                            Price = 250
                        },
                        new
                        {
                            Id = 7,
                            Description = "...",
                            PersonId = 4,
                            Price = 260
                        },
                        new
                        {
                            Id = 8,
                            Description = "...",
                            PersonId = 4,
                            Price = 270
                        },
                        new
                        {
                            Id = 9,
                            Description = "...",
                            PersonId = 3,
                            Price = 270
                        },
                        new
                        {
                            Id = 10,
                            Description = "...",
                            PersonId = 3,
                            Price = 280
                        });
                });

            modelBuilder.Entity("Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Muhiyittin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sedrettin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mugime"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cucume"
                        });
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.HasOne("Person", "Person")
                        .WithMany("Orders")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Person", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
