// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Complex_Relational_Queries.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251202051027_mig_1")]
    partial class mig_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "...",
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "...",
                            PersonId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "...",
                            PersonId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "...",
                            PersonId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "...",
                            PersonId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "...",
                            PersonId = 3
                        },
                        new
                        {
                            Id = 7,
                            Description = "...",
                            PersonId = 4
                        },
                        new
                        {
                            Id = 8,
                            Description = "...",
                            PersonId = 4
                        },
                        new
                        {
                            Id = 9,
                            Description = "...",
                            PersonId = 3
                        },
                        new
                        {
                            Id = 10,
                            Description = "...",
                            PersonId = 3
                        });
                });

            modelBuilder.Entity("Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gender = 1,
                            Name = "Muhiyittin"
                        },
                        new
                        {
                            Id = 2,
                            Gender = 1,
                            Name = "Sedrettin"
                        },
                        new
                        {
                            Id = 3,
                            Gender = 2,
                            Name = "Mugime"
                        },
                        new
                        {
                            Id = 4,
                            Gender = 2,
                            Name = "Cucume"
                        });
                });

            modelBuilder.Entity("Photo", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Url = "/photo1"
                        },
                        new
                        {
                            PersonId = 2,
                            Url = "/photo2"
                        },
                        new
                        {
                            PersonId = 3,
                            Url = "/photo3"
                        },
                        new
                        {
                            PersonId = 4,
                            Url = "/photo4"
                        });
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.HasOne("Person", "Person")
                        .WithMany("Orders")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Photo", b =>
                {
                    b.HasOne("Person", "Person")
                        .WithOne("Photo")
                        .HasForeignKey("Photo", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Person", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Photo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
