// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Value_Conversions.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251224123449_mig_1")]
    partial class mig_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gender = "M",
                            Name = "Abdulhamit"
                        },
                        new
                        {
                            Id = 2,
                            Gender = "M",
                            Name = "Eşref"
                        },
                        new
                        {
                            Id = 3,
                            Gender = "M",
                            Name = "Bartu"
                        },
                        new
                        {
                            Id = 4,
                            Gender = "F",
                            Name = "Cucume"
                        },
                        new
                        {
                            Id = 5,
                            Gender = "F",
                            Name = "Halime"
                        },
                        new
                        {
                            Id = 6,
                            Gender = "F",
                            Name = "Keriye"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
